#!/usr/bin/env python3
"""
gen-manifest-from-kb.py - emit a compare-matrix manifest from portage-ng kb.raw

Reads ordered_entry/3 facts from kb.raw (or kb.qlf via swipl if --qlf is
passed) and writes one cat/pn atom per line — the same shape compare-matrix
expects.

Default input is the baseline kb at /srv/tinderbox-ng/baseline/opt/portage-ng/
Knowledge/kb.raw on the VM; override with --kb.

Example:
  contrib/gen-manifest-from-kb.py \\
      --kb /srv/tinderbox-ng/baseline/opt/portage-ng/Knowledge/kb.raw \\
      --out share/tinderbox-ng/manifest-all-packages.txt
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ORDERED_ENTRY_RE = re.compile(
    r"^ordered_entry\(portage,'([^']+)'"
)


def split_pn_ver(cpv: str) -> tuple[str, str] | None:
    """Split cat/pn-ver into (cat/pn, ver) using PMS left-to-right rule."""
    if "/" not in cpv:
        return None
    cat, rest = cpv.split("/", 1)
    pn = rest
    ver = ""
    for i, ch in enumerate(rest):
        if ch == "-" and i + 1 < len(rest) and rest[i + 1].isdigit():
            pn = rest[:i]
            ver = rest[i + 1 :]
            break
    if not pn:
        return None
    return f"{cat}/{pn}", ver


def atoms_from_kb_text(text: str) -> set[str]:
    atoms: set[str] = set()
    for line in text.splitlines():
        m = ORDERED_ENTRY_RE.match(line)
        if not m:
            continue
        split = split_pn_ver(m.group(1))
        if split:
            atoms.add(split[0])
    return atoms


def read_kb_raw(path: Path) -> str:
    return path.read_text(errors="replace")


def read_kb_qlf(path: Path) -> str:
    # Dump ordered_entry/3 heads as text via a one-liner consult.
    script = f"""
:- set_prolog_flag(encoding, utf8).
:- consult('{path.as_posix()}').
:- dynamic(ordered_entry/5).
findall(CPV, ordered_entry(portage, CPV, _, _, _), CPVs),
        sort(CPVs, Sorted),
        forall(member(C, Sorted), format('ordered_entry(portage,~q).~n', [C])),
        halt.
"""
    proc = subprocess.run(
        ["swipl", "--no-signals", "-q"],
        input=script,
        text=True,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"swipl failed reading {path} (exit {proc.returncode})")
    return proc.stdout


def write_manifest(
    out_path: Path,
    atoms: list[str],
    *,
    kb_path: Path,
    tree_commit: str | None,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = [
        "# Generated by contrib/gen-manifest-from-kb.py",
        f"# kb: {kb_path}",
    ]
    if tree_commit:
        header.append(f"# portage-tree: {tree_commit}")
    header.extend([
        f"# generated: {now}",
        f"# entries: {len(atoms)}",
        "#",
        "# One cat/pn atom per line for compare-matrix / tinderbox-ng continue.",
        "# Derived from portage-ng ordered_entry facts (unique cat/pn).",
        "",
    ])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header + atoms) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--kb",
        type=Path,
        default=Path("/srv/tinderbox-ng/baseline/opt/portage-ng/Knowledge/kb.raw"),
        help="Path to kb.raw (default: baseline kb.raw on the VM)",
    )
    ap.add_argument(
        "--tree-commit",
        type=Path,
        default=Path("/srv/tinderbox-ng/shared/portage-tree.commit"),
        help="Optional portage-tree.commit file to record in the header",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path("share/tinderbox-ng/manifest-all-packages.txt"),
        help="Output manifest path",
    )
    ap.add_argument(
        "--qlf",
        action="store_true",
        help="Read kb.qlf via swipl instead of parsing kb.raw directly",
    )
    args = ap.parse_args()

    if not args.kb.is_file():
        raise SystemExit(f"kb not found: {args.kb}")

    if args.qlf:
        text = read_kb_qlf(args.kb)
    else:
        text = read_kb_raw(args.kb)

    atoms = sorted(atoms_from_kb_text(text))
    if not atoms:
        raise SystemExit(f"no ordered_entry atoms found in {args.kb}")

    tree_commit = None
    if args.tree_commit.is_file():
        tree_commit = args.tree_commit.read_text().strip().splitlines()[0]

    write_manifest(args.out, atoms, kb_path=args.kb.resolve(), tree_commit=tree_commit)
    print(f"wrote {len(atoms)} atoms -> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
