#!/usr/bin/env python3
"""
consolidate-phase-stats.py
==========================

Build a *master* phase_stats.pl by aggregating the per-session phase_stats.pl
files that `tinderbox-ng compare` salvages into each compare session's log
directory.

Canonical input layout
----------------------

Each `tinderbox-ng compare --build` session has portage-ng emit
`Knowledge/phase_stats.pl` inside the session's upper layer, and
`_compare_salvage_phase_stats` (in `bin/tinderbox-ng`) copies that file out
to `<logdir>/phase_stats.pl` immediately after the build pass — so it sits
alongside the plan/build/target logs in the same per-session directory.
Across a manifest you therefore end up with exactly one phase_stats.pl per
compare session, all under:

    /srv/tinderbox-ng/logs/compare-<label>-<stamp>/phase_stats.pl

This script's job is to fold those per-session files into a single master
phase_stats.pl that can be dropped in as the next portage-ng instance's
`Knowledge/phase_stats.pl` to seed its forecasting tables (see
`ebuild_exec:load_phase_stats/0` and `ebuild_exec:expected_phase_stats/4`).

The walk strategy ("recursively scan --src for files literally named
phase_stats.pl") is just a robust way to handle every layout —
`tinderbox-ng phase-stats` always points us at one of:
  - a matrix run dir (with the logs dir as a fallback),
  - the logs dir directly,
  - or an arbitrary tree (archives, cross-machine consolidation).
There is no chance of picking up unrelated files by accident: portage-ng
only ever writes this filename for forecasting facts.

Per-session input format (one fact per line, generated by
ebuild_exec:save_phase_stats/0):

    phase_bytes('cat/pn-ver', PhaseAtom, IntegerBytes).
    phase_seconds('cat/pn-ver', PhaseAtom, FloatSeconds).

Each per-session file holds at most ONE observation per (Entry, Phase) — the
last one observed in that session. Across N sessions that built the same
package we therefore see up to N independent observations of every phase. We
aggregate those observations into a single representative value per
(Entry, Phase) and emit a Prolog file in the same format.

Aggregators (choose with --aggregator):
  median  Robust against cold-cache outliers and dirty disks  (default).
  mean    Plain average of all observations.
  max     Worst-case envelope; useful for upper-bound progress bars.
  p75     75th percentile  (slightly pessimistic forecast).
  p90     90th percentile  (very pessimistic forecast).

Completed-build filter (--require-phase, default: merge):
  Within each per-session file, an entry's facts are ingested only when
  that same file also holds a fact for the required phase (default
  `merge`) for that entry. This guards against three distortion sources
  observed in full-tree build runs:

    1. Failure-truncated observations: portage-ng's
       ebuild_exec:record_phase_stats/4 records a phase's duration even
       when the phase FAILED, so an aborted gcc compile leaves a
       seconds-long `compile` fact that would poison the forecast. A
       failed build never reaches `merge`, so requiring a same-session
       merge fact drops every truncated observation.
    2. Baseline-seed carry-over: sessions start from a baseline whose
       Knowledge/phase_stats.pl may be pre-seeded; load_phase_stats
       re-saves those facts verbatim into every session file,
       multiplying foreign observations by the session count. Seed
       entries were never built in-session, so they have no in-session
       merge fact and are dropped (unless genuinely rebuilt, in which
       case the fresh observations rightly win).
    3. Binpkg deploys: these are structurally absent (the binpkg
       qmerge fast-path bypasses phase recording entirely), but the
       filter also guarantees nothing binpkg-shaped can ever slip in:
       a deploy records no phases at all, let alone `merge`.

  Use `--require-phase none` to disable and ingest everything.

A `%!` comment header records aggregator, source-file count, and per-entry
observation counts so the file is self-describing without breaking Prolog
parsers (`%!` lines are pure comments).

Usage:
  consolidate-phase-stats.py --src DIR  [--out FILE]
                             [--aggregator median|mean|max|p75|p90]
                             [--min-observations N]
                             [--exclude-glob PATTERN ...]

The output file is excluded from the input scan automatically, so it's
safe to write the master file inside the same tree as its inputs.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import re
import statistics
import sys
from collections import defaultdict
from pathlib import Path
from typing import Callable, Dict, Iterator, List, Tuple

# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

# phase_stats.pl is generated machine-side by ebuild_exec:save_phase_stats/0.
# The `entry` is always single-quoted (cat/pn-ver may contain '+', so format
# ~q quotes it for Prolog round-tripping). The `phase` atom is always lower
# case and never needs quoting. A regex parser is sufficient.
_BYTES_RE = re.compile(
    r"^\s*phase_bytes\(\s*'([^']*)'\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*,"
    r"\s*(-?\d+)\s*\)\s*\.\s*(?:%.*)?$"
)
_SECS_RE = re.compile(
    r"^\s*phase_seconds\(\s*'([^']*)'\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*,"
    r"\s*(-?\d+(?:\.\d+)?)\s*\)\s*\.\s*(?:%.*)?$"
)


def parse_phase_stats_file(path: Path) -> Iterator[Tuple[str, str, str, float]]:
    """Yield (kind, entry, phase, value) for every recognised fact in `path`.

    `kind` is one of {"bytes", "seconds"}. Lines that don't match either
    fact shape (comments, blank lines, malformed entries) are silently
    skipped — the per-session writer is well-behaved, so tolerating the
    odd hand-edit is fine.
    """
    try:
        with path.open("r", errors="replace") as fh:
            for line in fh:
                m = _BYTES_RE.match(line)
                if m:
                    yield ("bytes", m.group(1), m.group(2), float(m.group(3)))
                    continue
                m = _SECS_RE.match(line)
                if m:
                    yield ("seconds", m.group(1), m.group(2), float(m.group(3)))
    except OSError as e:
        print(f"warning: cannot read {path}: {e}", file=sys.stderr)


def ingest_file(
    path: Path,
    require_phase: str,
    bytes_obs: Dict[Tuple[str, str], List[float]],
    secs_obs: Dict[Tuple[str, str], List[float]],
) -> Tuple[int, int]:
    """Parse one per-session file and fold its facts into the global
    observation maps, honouring the completed-build filter.

    When `require_phase` is non-empty, an entry's facts are kept only if
    the SAME file holds at least one fact (bytes or seconds) for that
    entry at `require_phase`. Returns (kept_facts, dropped_facts).
    """
    facts = list(parse_phase_stats_file(path))
    if require_phase:
        eligible = {entry for (_k, entry, phase, _v) in facts
                    if phase == require_phase}
    else:
        eligible = None

    kept = dropped = 0
    for kind, entry, phase, val in facts:
        if eligible is not None and entry not in eligible:
            dropped += 1
            continue
        if kind == "bytes":
            bytes_obs[(entry, phase)].append(val)
        else:
            secs_obs[(entry, phase)].append(val)
        kept += 1
    return kept, dropped


def find_phase_stats_files(src: Path, excludes: List[str]) -> List[Path]:
    """Recursively collect every file literally named `phase_stats.pl`
    under `src`, with optional fnmatch-style exclusions on the absolute
    path."""
    out: List[Path] = []
    for root, _dirs, files in os.walk(src):
        for f in files:
            if f != "phase_stats.pl":
                continue
            p = Path(root) / f
            sp = str(p)
            if any(fnmatch.fnmatch(sp, pat) for pat in excludes):
                continue
            out.append(p)
    out.sort()
    return out


# ---------------------------------------------------------------------------
# Aggregators
# ---------------------------------------------------------------------------

def _percentile(values: List[float], q: float) -> float:
    # statistics.quantiles needs >=2 data points; fall back gracefully.
    if not values:
        return 0.0
    if len(values) == 1:
        return float(values[0])
    # method='inclusive' (R-7) matches numpy.percentile default and is
    # the "obvious" definition for human consumers.
    qs = statistics.quantiles(values, n=100, method="inclusive")
    idx = max(1, min(99, int(round(q)))) - 1
    return float(qs[idx])


_AGGREGATORS: Dict[str, Callable[[List[float]], float]] = {
    "median": lambda xs: float(statistics.median(xs)),
    "mean":   lambda xs: float(statistics.fmean(xs)),
    "max":    lambda xs: float(max(xs)),
    "p75":    lambda xs: _percentile(xs, 75.0),
    "p90":    lambda xs: _percentile(xs, 90.0),
}


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

# Writer emits phase_bytes lines for each (entry, phase) followed by
# phase_seconds lines for the same key, grouped per entry alphabetically.
# This matches the layout that ebuild_exec:save_phase_stats/0 would itself
# produce for an equivalent in-memory state, so the file diffs cleanly
# against per-session files.

# Stable phase order: matches the canonical Gentoo ebuild phase pipeline,
# so the file reads chronologically per package.
_PHASE_ORDER = [
    "clean",
    "setup",
    "fetch",
    "unpack",
    "prepare",
    "configure",
    "compile",
    "test",
    "install",
    "preinst",
    "merge",
    "postinst",
    "qmerge",
]


def _phase_sort_key(phase: str) -> Tuple[int, str]:
    try:
        return (_PHASE_ORDER.index(phase), phase)
    except ValueError:
        return (len(_PHASE_ORDER), phase)


def write_master(
    out_path: Path,
    bytes_obs: Dict[Tuple[str, str], List[float]],
    secs_obs: Dict[Tuple[str, str], List[float]],
    aggregator_name: str,
    min_obs: int,
    n_sources: int,
    require_phase: str = "",
) -> Tuple[int, int, int]:
    """Aggregate observations and write the master file. Returns
    (entry_count, bytes_facts, seconds_facts)."""

    agg = _AGGREGATORS[aggregator_name]

    entries = sorted({entry for (entry, _phase) in (*bytes_obs.keys(), *secs_obs.keys())})

    bytes_count = 0
    secs_count = 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write(f"%! Master phase_stats.pl\n")
        f.write(f"%!   aggregator     : {aggregator_name}\n")
        f.write(f"%!   source_files   : {n_sources}\n")
        f.write(f"%!   entries        : {len(entries)}\n")
        f.write(f"%!   min_observations: {min_obs}\n")
        f.write(f"%!   require_phase  : {require_phase or '(none)'}\n")
        f.write("%!\n")
        f.write("%! Format matches portage-ng's ebuild_exec:save_phase_stats/0.\n")
        f.write("%! Drop in as Knowledge/phase_stats.pl to seed forecasting tables.\n")
        # Group by entry (phase_bytes + phase_seconds for the same package
        # together) for human readability. Declare discontiguous so the
        # file consults cleanly via swipl's `[file].` form too. portage-ng
        # itself uses read_term/2 in a loop and doesn't care either way.
        f.write(":- discontiguous phase_bytes/3, phase_seconds/3.\n\n")

        for entry in entries:
            phases = sorted(
                {p for (e, p) in (*bytes_obs.keys(), *secs_obs.keys()) if e == entry},
                key=_phase_sort_key,
            )

            # Emit a per-entry header summarising observation counts.
            n_b = max((len(bytes_obs.get((entry, p), [])) for p in phases), default=0)
            n_s = max((len(secs_obs.get((entry, p), [])) for p in phases), default=0)
            f.write(f"%! {entry}  (bytes_obs<= {n_b}, secs_obs<= {n_s})\n")

            for phase in phases:
                obs = bytes_obs.get((entry, phase), [])
                if len(obs) >= min_obs:
                    v = int(round(agg(obs)))
                    f.write(f"phase_bytes('{entry}', {phase}, {v}).\n")
                    bytes_count += 1
            for phase in phases:
                obs = secs_obs.get((entry, phase), [])
                if len(obs) >= min_obs:
                    v = agg(obs)
                    # 6 decimal places matches portage-ng's `~f` default.
                    f.write(f"phase_seconds('{entry}', {phase}, {v:.6f}).\n")
                    secs_count += 1
            f.write("\n")

    return (len(entries), bytes_count, secs_count)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: List[str]) -> int:
    p = argparse.ArgumentParser(
        prog="consolidate-phase-stats.py",
        description="Aggregate per-session phase_stats.pl files into a "
                    "master phase_stats.pl for portage-ng forecasting.",
    )
    p.add_argument("--src", required=True,
                   help="Directory to scan recursively for phase_stats.pl files.")
    p.add_argument("--out", required=True,
                   help="Output path for the master phase_stats.pl.")
    p.add_argument("--aggregator", choices=sorted(_AGGREGATORS.keys()),
                   default="median",
                   help="Aggregation function across observations (default: median).")
    p.add_argument("--min-observations", type=int, default=1, metavar="N",
                   help="Drop (Entry, Phase) buckets with fewer than N "
                        "observations (default: 1, keep singletons).")
    p.add_argument("--require-phase", default="merge", metavar="PHASE",
                   help="Per session file, ingest an entry's facts only when "
                        "that file also holds a fact for PHASE for the same "
                        "entry (default: merge -- keeps only completed source "
                        "builds; excludes failure-truncated observations, "
                        "baseline-seed carry-over, and binpkg deploys). "
                        "Use 'none' to disable.")
    p.add_argument("--exclude-glob", action="append", default=[], metavar="PATTERN",
                   help="fnmatch pattern (matched against absolute path) to "
                        "skip during the input scan. Repeatable.")
    p.add_argument("--quiet", action="store_true",
                   help="Suppress progress output.")

    args = p.parse_args(argv)

    src = Path(args.src).resolve()
    if not src.is_dir():
        print(f"error: --src is not a directory: {src}", file=sys.stderr)
        return 2
    out = Path(args.out).resolve()

    # Always exclude the output file from input.
    excludes = list(args.exclude_glob) + [str(out)]

    sources = find_phase_stats_files(src, excludes)
    if not sources:
        print(f"error: no phase_stats.pl files found under {src}", file=sys.stderr)
        return 1
    if not args.quiet:
        print(f"[phase-stats] scanning {len(sources)} source file(s) under {src}",
              file=sys.stderr)

    require_phase = "" if args.require_phase == "none" else args.require_phase

    bytes_obs: Dict[Tuple[str, str], List[float]] = defaultdict(list)
    secs_obs:  Dict[Tuple[str, str], List[float]] = defaultdict(list)

    total_kept = total_dropped = 0
    for sf in sources:
        kept, dropped = ingest_file(sf, require_phase, bytes_obs, secs_obs)
        total_kept += kept
        total_dropped += dropped

    if not args.quiet and require_phase:
        print(f"[phase-stats] require-phase={require_phase}: "
              f"kept {total_kept} fact(s), dropped {total_dropped}",
              file=sys.stderr)

    if not bytes_obs and not secs_obs:
        print("error: no parsable facts in any source file", file=sys.stderr)
        return 1

    entries, n_b, n_s = write_master(
        out_path=out,
        bytes_obs=bytes_obs,
        secs_obs=secs_obs,
        aggregator_name=args.aggregator,
        min_obs=args.min_observations,
        n_sources=len(sources),
        require_phase=require_phase,
    )

    if not args.quiet:
        # Quick observation-count distribution for operator visibility.
        all_counts = [len(v) for v in bytes_obs.values()] + \
                     [len(v) for v in secs_obs.values()]
        if all_counts:
            mn = min(all_counts); mx = max(all_counts)
            md = statistics.median(all_counts)
        else:
            mn = mx = md = 0
        print(f"[phase-stats] entries: {entries}  "
              f"phase_bytes facts: {n_b}  phase_seconds facts: {n_s}",
              file=sys.stderr)
        print(f"[phase-stats] observations per (entry,phase): "
              f"min={mn}  median={md}  max={mx}",
              file=sys.stderr)
        print(f"[phase-stats] wrote {out}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
